project:
  type: book
  output-dir: _output

# website:
#   title: Quarto Test

#   navbar:
#     title: Quarto Test
#     left:
#       - href: index.qmd
#         text: Home
#       - href: introduction.qmd
#         text: Introduction
#       - href: some_notebook.qmd
#         text: Some Notebook

book:
  title: "Numerical Methods for Quantum Optics and Open Quantum Systems"
  author:
    - name: Alberto Mercurio
    - name: Daniele De Bernardis
  chapters:
    - index.qmd
    - introduction.qmd

# default format for all files
format:
  html:
    theme:
      light: flatly
      dark: darkly
    highlight-style: atom-one
    css: styles.css
    toc: true
    published-title: Last Update
    date-format: iso
    code-line-numbers: true
    colorlinks: true
    footnotes-hover: true
    fig-align: center
    fig-responsive: true

jupyter: python3

execute:
  eval: true
