project:
  type: book

book:
  title: "Numerical Methods for Quantum Optics and Open Quantum Systems"
  author:
    - name: Alberto Mercurio
  date: today
  downloads: [pdf]
  chapters:
    - index.qmd

# default format for all files
format:
  html:
    toc: true
  pdf:
    documentclass: scrreprt
    toc: true

jupyter: python3

execute:
  eval: true
