project:
  type: book
  execute-dir: project

book:
  title: "Numerical Methods for Quantum Optics and Open Quantum Systems"
  author:
    - name: Alberto Mercurio
  chapters:
    - index.qmd

# default format for all files
format:
  html:
    toc: true

jupyter: python3

execute:
  eval: true
